export const movies = [
  { id:'1', title:'Scarlet Night', year:2023, rating:8.2, genre:['Drama','Thriller'], poster:'/assets/poster1.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A quiet city. A louder secret.', type:'movie', featured:false },
  { id:'2', title:'Moonlight Heist', year:2024, rating:7.6, genre:['Action','Crime'], poster:'/assets/poster2.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'High stakes and neon lights.', type:'movie', featured:false },
  { id:'3', title:'Tomato Sunrise', year:2021, rating:7.9, genre:['Comedy'], poster:'/assets/poster3.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A funny take on life and food.', type:'movie', featured:false }
  ,
  { id:'4', title:'Dune: Part Two', year:2024, rating:8.9, genre:['Ciencia Ficción'], poster:'https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Paul Atreides se une a los Fremen y enfrenta una elección entre el amor y el destino del universo.', type:'movie', featured:true },
  { id:'5', title:'Oppenheimer', year:2023, rating:8.8, genre:['Biográfica','Drama'], poster:'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'La vida de J. Robert Oppenheimer y las consecuencias morales de la bomba atómica.', type:'movie', featured:true },
  { id:'6', title:'Spider-Man: Across the Spider-Verse', year:2023, rating:9.0, genre:['Animación','Acción'], poster:'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Miles Morales viaja por el multiverso y conoce nuevas versiones de Spider‑Man.', type:'movie', featured:true },
  { id:'7', title:'The Batman', year:2022, rating:8.1, genre:['Acción','Crimen'], poster:'https://upload.wikimedia.org/wikipedia/en/f/ff/The_Batman_%28film%29_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'En su segundo año, Batman destapa la corrupción en Gotham y su vínculo con su familia.', type:'movie', featured:false },
  { id:'8', title:'Inception', year:2021, rating:8.8, genre:['Ciencia Ficción','Thriller'], poster:'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Un ladrón se adentra en los sueños para implantar una idea en el subconsciente.', type:'movie', featured:false },
  { id:'9', title:'Interstellar', year:2022, rating:8.6, genre:['Aventura','Ciencia Ficción'], poster:'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Un equipo viaja a través de un agujero de gusano para asegurar la supervivencia humana.', type:'movie', featured:false },
  // Series añadidas
  { id:'s1', title:'The Last of Us', year:2023, rating:8.8, genre:['Drama','Aventura'], poster:'https://upload.wikimedia.org/wikipedia/en/6/6c/The_Last_of_Us_TV_series_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Un viaje por un mundo post‑pandémico.', type:'series', featured:true },
  { id:'s2', title:'Severance', year:2022, rating:8.7, genre:['Ciencia Ficción','Misterio'], poster:'https://upload.wikimedia.org/wikipedia/en/1/1e/Severance_TV_series.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Separar la vida laboral y personal tiene un precio.', type:'series', featured:false },
  { id:'s3', title:'The Last Kingdom', year:2023, rating:8.5, genre:['Drama'], poster:'https://m.media-amazon.com/images/I/71b5mDrvCyL._UF894,1000_QL80_.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Reinos en guerra y la resistencia de Wessex bajo Alfredo el Grande.', type:'series', featured:false },
  { id:'s4', title:'Stranger Things', year:2023, rating:9.1, genre:['Ciencia Ficción'], poster:'https://www.nacionflix.com/__export/1679947679522/sites/debate/img/2023/03/27/stranger-things-5-netflix.jpg_593059942.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'En Hawkins, Indiana, surge la amenaza del Upside Down.', type:'series', featured:true },
  { id:'s5', title:'The Crown', year:2022, rating:8.7, genre:['Histórica'], poster:'https://www.nouveautes-tele.com/wp-content/uploads/2022/09/thecrown.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Drama histórico sobre el reinado de Isabel II.', type:'series', featured:false },
  { id:'s6', title:'Wednesday', year:2024, rating:8.2, genre:['Comedia'], poster:'https://hips.hearstapps.com/hmg-prod/images/miercoles-netflix-3-1669199747.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Wednesday Addams en la Academia Nunca Más.', type:'series', featured:false },
  { id:'s7', title:'Breaking Bad', year:2021, rating:9.5, genre:['Drama'], poster:'https://m.media-amazon.com/images/I/71HvGDa1ZLL._UF1000,1000_QL80_.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Un profesor con cáncer fabrica metanfetamina para su familia.', type:'series', featured:true },
  { id:'s8', title:'The Mandalorian', year:2024, rating:8.8, genre:['Ciencia Ficción'], poster:'https://4kwallpapers.com/images/walls/thumbs_3t/934.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Un cazarrecompensas mandaloriano tras la caída del Imperio.', type:'series', featured:false }
]
