export const movies = [
  { id:'1', title:'Scarlet Night', year:2023, rating:8.2, genre:['Drama','Thriller'], poster:'/assets/poster1.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A quiet city. A louder secret.', type:'movie', featured:false },
  { id:'2', title:'Moonlight Heist', year:2024, rating:7.6, genre:['Action','Crime'], poster:'/assets/poster2.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'High stakes and neon lights.', type:'movie', featured:false },
  { id:'3', title:'Tomato Sunrise', year:2021, rating:7.9, genre:['Comedy'], poster:'/assets/poster3.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A funny take on life and food.', type:'movie', featured:false }
  ,
  { id:'4', title:'Dune: Part Two', year:2024, rating:8.6, genre:['Sci-Fi','Adventure'], poster:'https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two_poster.jpeg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'The saga continues on Arrakis.', type:'movie', featured:true },
  { id:'5', title:'Oppenheimer', year:2023, rating:8.4, genre:['Biography','Drama'], poster:'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'The story of J. Robert Oppenheimer.', type:'movie', featured:true },
  { id:'6', title:'Spider-Man: Across the Spider-Verse', year:2023, rating:8.7, genre:['Animation','Action'], poster:'https://upload.wikimedia.org/wikipedia/en/b/b4/Spider-Man-_Across_the_Spider-Verse_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Miles Morales returns for a multiverse adventure.', type:'movie', featured:true },
  { id:'7', title:'The Batman', year:2022, rating:7.8, genre:['Action','Crime'], poster:'https://upload.wikimedia.org/wikipedia/en/f/ff/The_Batman_%28film%29_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A darker detective story in Gotham.', type:'movie', featured:false },
  { id:'8', title:'Inception', year:2010, rating:8.8, genre:['Sci-Fi','Thriller'], poster:'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A thief who steals corporate secrets through dream-sharing technology.', type:'movie', featured:false },
  { id:'9', title:'Interstellar', year:2014, rating:8.6, genre:['Sci-Fi','Adventure'], poster:'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A team travels through a wormhole in space in an attempt to ensure humanity’s survival.', type:'movie', featured:false },
  // Series añadidas
  { id:'s1', title:'The Last of Us', year:2023, rating:8.8, genre:['Drama','Adventure'], poster:'https://upload.wikimedia.org/wikipedia/en/6/6c/The_Last_of_Us_TV_series_poster.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'A journey through a post-pandemic world.', type:'series', featured:true },
  { id:'s2', title:'Severance', year:2022, rating:8.7, genre:['Sci-Fi','Mystery'], poster:'https://upload.wikimedia.org/wikipedia/en/1/1e/Severance_TV_series.jpg', trailer:'https://www.youtube.com/embed/dQw4w9WgXcQ', overview:'Work-life balance pushed to the limit.', type:'series', featured:false }
]
